services:
  # servicio documento (.net)
  document-service:
    build:
      context: .  # ← Contexto desde la raíz del proyecto
      dockerfile: document-service/src/Document.API/Dockerfile
    container_name: document-service
    ports:
      - "5001:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Uri=amqp://admin:admin123@rabbitmq:5672/
    networks:
      - multiservices-network

  # minio storage
  minio:
    image: minio/minio:latest
    container_name: minio-multiservicios
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - multiservices-network

  # servicio user (Nest)
  user-service:
    container_name: user-service-multiservicios
    build:
      context: ../user-service
      dockerfile: Dockerfile
    image: user-api:latest
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    # environment:
    #   DB_HOST: ${DB_HOST}
    #   DB_PORT: ${DB_PORT}
    #   DB_USER: ${DB_USER}
    #   DB_PASS: ${DB_PASS}
    #   DB_NAME: ${DB_NAME}
    env_file:
      - ../user-service/.env 
    networks:
      - multiservices-network

  # servicio auth (.Net)
  auth-service:
    container_name: auth-service-multiservicios
    build:
      context: ../auth-service/src/Auth.API
      dockerfile: Dockerfile
    image: auth-api:latest
    ports:
      - "8083:8083"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8083  
    networks:
      - multiservices-network

  # keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-multiservicios
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloakdb
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - multiservices-network

  # motor postgres
  postgres:
    image: postgres:16
    container_name: postgres-multiservicios
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloakdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - multiservices-network

  # PGAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-multiservicios
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - multiservices-network

  #  Rabbitmq 
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-multiservicios
    hostname: rabbitmq
    ports:
     - "5672:5672" #puerto de amqp
     - "15672:15672" #puerto de management UI 
    environment:
     RABBITMQ_DEFAULT_USER: admin
     RABBITMQ_DEFAULT_PASS: admin123
    volumes:
     - rabbitmq-data:/var/lib/rabbitmq
    networks:
     - multiservices-network 

# formato general : amqp://usuario:password@host:puerto/nombre_virtual_host osea = amqp://admin:admin123@rabbitmq:5672/

networks:
  multiservices-network:
    driver: bridge

volumes:
  minio-data: 
  pgdata:
  keycloak_data:
  rabbitmq-data:
