version: "3.9"

services:
  #servicio documento (.net)
  document-service:
    container_name: document-service-multiservicios
    build:
      context: ../document-service/src/Document.API
      dockerfile: Dockerfile
    image: document-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - minio
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - multiservices-network

  minio:
    image: minio/minio:latest
    container_name: minio-multiservicios
    ports:
      - "9000:9000"  # API #recursos
      - "9001:9001"  # Consola de administraci√≥n admin
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - multiservices-network

  #servicio de usuario(nest)
  user-service:
    container_name: user-service-multiservicios
    build:
      context: ../user-service
      dockerfile: Dockerfile
    image: user-api:latest
    ports:
      - "3000:3001"
    depends_on:
      - postgres
    environment:
      BDATABASE_URL: "postgresql://admin:admin@postgres:5432/userdb"
    networks:
      - multiservices-network

  postgres:
    image: postgres:16
    container_name: postgres-multiservicios
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - multiservices-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-multiservicios
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - multiservices-network

networks:
  multiservices-network:
    driver: bridge

volumes:
  minio-data:
  pgdata:
